/*
SWAIN API

Testing DynamicAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/mobixdev/SWAIN-GO_SDK"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_DynamicAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration("", "")
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DynamicAPIService ModelCountPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var model string

		resp, httpRes, err := apiClient.DynamicAPI.Count(context.Background(), model).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicAPIService ModelFilterPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var model string

		resp, httpRes, err := apiClient.DynamicAPI.GetWhere(context.Background(), model).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicAPIService ModelGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var model string

		resp, httpRes, err := apiClient.DynamicAPI.GetAll(context.Background(), model).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicAPIService ModelIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var model string
		var id string

		resp, httpRes, err := apiClient.DynamicAPI.DeleteById(context.Background(), model, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicAPIService ModelIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var model string
		var id string

		resp, httpRes, err := apiClient.DynamicAPI.GetById(context.Background(), model, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicAPIService ModelIdPut", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var model string
		var id string

		resp, httpRes, err := apiClient.DynamicAPI.UpdateById(context.Background(), model, id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DynamicAPIService ModelPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var model string

		resp, httpRes, err := apiClient.DynamicAPI.Create(context.Background(), model).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
