/*
SWAIN API

Testing BulkOperationsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_BulkOperationsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration("", "")
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BulkOperationsAPIService ModelFilterDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var model string

		resp, httpRes, err := apiClient.BulkOperationsAPI.DeleteWhere(context.Background(), model).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BulkOperationsAPIService ModelFilterPut", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var model string

		resp, httpRes, err := apiClient.BulkOperationsAPI.UpdateWhere(context.Background(), model).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
