/*
SWAIN API

A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiUpdateFilterPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiUpdateFilterPayload{}

// ApiUpdateFilterPayload struct for ApiUpdateFilterPayload
type ApiUpdateFilterPayload struct {
	Expressions []map[string]interface{} `json:"expressions,omitempty"`
	UpdateData map[string]interface{} `json:"updateData,omitempty"`
}

// NewApiUpdateFilterPayload instantiates a new ApiUpdateFilterPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiUpdateFilterPayload() *ApiUpdateFilterPayload {
	this := ApiUpdateFilterPayload{}
	return &this
}

// NewApiUpdateFilterPayloadWithDefaults instantiates a new ApiUpdateFilterPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiUpdateFilterPayloadWithDefaults() *ApiUpdateFilterPayload {
	this := ApiUpdateFilterPayload{}
	return &this
}

// GetExpressions returns the Expressions field value if set, zero value otherwise.
func (o *ApiUpdateFilterPayload) GetExpressions() []map[string]interface{} {
	if o == nil || IsNil(o.Expressions) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Expressions
}

// GetExpressionsOk returns a tuple with the Expressions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiUpdateFilterPayload) GetExpressionsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Expressions) {
		return nil, false
	}
	return o.Expressions, true
}

// HasExpressions returns a boolean if a field has been set.
func (o *ApiUpdateFilterPayload) HasExpressions() bool {
	if o != nil && !IsNil(o.Expressions) {
		return true
	}

	return false
}

// SetExpressions gets a reference to the given []map[string]interface{} and assigns it to the Expressions field.
func (o *ApiUpdateFilterPayload) SetExpressions(v []map[string]interface{}) {
	o.Expressions = v
}

// GetUpdateData returns the UpdateData field value if set, zero value otherwise.
func (o *ApiUpdateFilterPayload) GetUpdateData() map[string]interface{} {
	if o == nil || IsNil(o.UpdateData) {
		var ret map[string]interface{}
		return ret
	}
	return o.UpdateData
}

// GetUpdateDataOk returns a tuple with the UpdateData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiUpdateFilterPayload) GetUpdateDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.UpdateData) {
		return map[string]interface{}{}, false
	}
	return o.UpdateData, true
}

// HasUpdateData returns a boolean if a field has been set.
func (o *ApiUpdateFilterPayload) HasUpdateData() bool {
	if o != nil && !IsNil(o.UpdateData) {
		return true
	}

	return false
}

// SetUpdateData gets a reference to the given map[string]interface{} and assigns it to the UpdateData field.
func (o *ApiUpdateFilterPayload) SetUpdateData(v map[string]interface{}) {
	o.UpdateData = v
}

func (o ApiUpdateFilterPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiUpdateFilterPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Expressions) {
		toSerialize["expressions"] = o.Expressions
	}
	if !IsNil(o.UpdateData) {
		toSerialize["updateData"] = o.UpdateData
	}
	return toSerialize, nil
}

type NullableApiUpdateFilterPayload struct {
	value *ApiUpdateFilterPayload
	isSet bool
}

func (v NullableApiUpdateFilterPayload) Get() *ApiUpdateFilterPayload {
	return v.value
}

func (v *NullableApiUpdateFilterPayload) Set(val *ApiUpdateFilterPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableApiUpdateFilterPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableApiUpdateFilterPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiUpdateFilterPayload(val *ApiUpdateFilterPayload) *NullableApiUpdateFilterPayload {
	return &NullableApiUpdateFilterPayload{value: val, isSet: true}
}

func (v NullableApiUpdateFilterPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiUpdateFilterPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


