/*
SWAIN API

A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole{}

// GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole struct for GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
type GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole struct {
	CreatedAt *string `json:"created_at,omitempty"`
	Description *string `json:"description,omitempty"`
	Id *int32 `json:"id,omitempty"`
	// Role name must be unique
	Name *string `json:"name,omitempty"`
	Permissions []GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission `json:"permissions,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	Users []GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser `json:"users,omitempty"`
}

// NewGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole instantiates a new GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole() *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole {
	this := GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole{}
	return &this
}

// NewGithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleWithDefaults instantiates a new GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComTakifouhalCrudsqlPkgInternalAuthModelsRoleWithDefaults() *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole {
	this := GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) SetName(v string) {
	o.Name = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetPermissions() []GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission {
	if o == nil || IsNil(o.Permissions) {
		var ret []GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetPermissionsOk() ([]GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission and assigns it to the Permissions field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) SetPermissions(v []GithubComTakifouhalCrudsqlPkgInternalAuthModelsPermission) {
	o.Permissions = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetUsers() []GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser {
	if o == nil || IsNil(o.Users) {
		var ret []GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) GetUsersOk() ([]GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser and assigns it to the Users field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) SetUsers(v []GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) {
	o.Users = v
}

func (o GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	return toSerialize, nil
}

type NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole struct {
	value *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
	isSet bool
}

func (v NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) Get() *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole {
	return v.value
}

func (v *NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) Set(val *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole(val *GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) *NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole {
	return &NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole{value: val, isSet: true}
}

func (v NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


