/*
SWAIN API

A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models SWAIN provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger/OpenAPI documentation - Multiple database support (SQL & NoSQL)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser{}

// GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser struct for GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
type GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser struct {
	AdditionalData map[string]interface{} `json:"additional_data,omitempty"`
	Anonymous *bool `json:"anonymous,omitempty"`
	Email *string `json:"email,omitempty"`
	Id *int32 `json:"id,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	LastLogin *string `json:"last_login,omitempty"`
	Name *string `json:"name,omitempty"`
	Roles []GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole `json:"roles,omitempty"`
}

// NewGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser instantiates a new GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser() *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser {
	this := GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser{}
	return &this
}

// NewGithubComTakifouhalCrudsqlPkgInternalAuthModelsUserWithDefaults instantiates a new GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGithubComTakifouhalCrudsqlPkgInternalAuthModelsUserWithDefaults() *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser {
	this := GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser{}
	return &this
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetAdditionalData() map[string]interface{} {
	if o == nil || IsNil(o.AdditionalData) {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetAdditionalDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given map[string]interface{} and assigns it to the AdditionalData field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) SetAdditionalData(v map[string]interface{}) {
	o.AdditionalData = v
}

// GetAnonymous returns the Anonymous field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetAnonymous() bool {
	if o == nil || IsNil(o.Anonymous) {
		var ret bool
		return ret
	}
	return *o.Anonymous
}

// GetAnonymousOk returns a tuple with the Anonymous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetAnonymousOk() (*bool, bool) {
	if o == nil || IsNil(o.Anonymous) {
		return nil, false
	}
	return o.Anonymous, true
}

// HasAnonymous returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) HasAnonymous() bool {
	if o != nil && !IsNil(o.Anonymous) {
		return true
	}

	return false
}

// SetAnonymous gets a reference to the given bool and assigns it to the Anonymous field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) SetAnonymous(v bool) {
	o.Anonymous = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) SetEmail(v string) {
	o.Email = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) SetId(v int32) {
	o.Id = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetLastLogin returns the LastLogin field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetLastLogin() string {
	if o == nil || IsNil(o.LastLogin) {
		var ret string
		return ret
	}
	return *o.LastLogin
}

// GetLastLoginOk returns a tuple with the LastLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetLastLoginOk() (*string, bool) {
	if o == nil || IsNil(o.LastLogin) {
		return nil, false
	}
	return o.LastLogin, true
}

// HasLastLogin returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) HasLastLogin() bool {
	if o != nil && !IsNil(o.LastLogin) {
		return true
	}

	return false
}

// SetLastLogin gets a reference to the given string and assigns it to the LastLogin field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) SetLastLogin(v string) {
	o.LastLogin = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) SetName(v string) {
	o.Name = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetRoles() []GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole {
	if o == nil || IsNil(o.Roles) {
		var ret []GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) GetRolesOk() ([]GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole and assigns it to the Roles field.
func (o *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) SetRoles(v []GithubComTakifouhalCrudsqlPkgInternalAuthModelsRole) {
	o.Roles = v
}

func (o GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdditionalData) {
		toSerialize["additional_data"] = o.AdditionalData
	}
	if !IsNil(o.Anonymous) {
		toSerialize["anonymous"] = o.Anonymous
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.LastLogin) {
		toSerialize["last_login"] = o.LastLogin
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	return toSerialize, nil
}

type NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser struct {
	value *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser
	isSet bool
}

func (v NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) Get() *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser {
	return v.value
}

func (v *NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) Set(val *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) {
	v.value = val
	v.isSet = true
}

func (v NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) IsSet() bool {
	return v.isSet
}

func (v *NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser(val *GithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) *NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser {
	return &NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser{value: val, isSet: true}
}

func (v NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGithubComTakifouhalCrudsqlPkgInternalAuthModelsUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


